name: Sync Inference Folder

on:
  push:
    branches:
      - main
    paths:
      - 'inference/**'

jobs:
  sync-inference:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1
        env:
          key: main
          branches: inference
          files: inference/
