name: Sync Inference Folder

on:
  push:
    branches:
      - main
    paths:
      - 'inference/**'

permissions:
  contents: write


jobs:

  sync-inference:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Copy inference folder from main to temp folder
        run: |
          mkdir -p temp_inference
          cp -r inference/* temp_inference/

      - name: Checkout inference branch
        run: |
          git fetch
          git checkout production

      - name: paste copies in inference
        run: cp -r temp_inference/* inference/

      - name: remove temp directory
        run: rm -rf temp_inference

      
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update inference folder from main branch"
          git push origin production
